apiVersion: v1
kind: Namespace
metadata:
  name: hacked
---
apiVersion: v1
kind: Service
metadata:
  name: hacked-svc
  namespace: hacked
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: hacked-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacked-app
  namespace: hacked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacked-app
  template:
    metadata:
      labels:
        app: hacked-app
    spec:
      containers:
      - name: hacked-app
        image: chrisley75/kubernetes-hacked-app:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: You've hacked the Kubernetes Cluster !
        - name: K8SURL
          value: CHANGE_K8SURL
        - name: K8STOKEN
          value: CHANGE_K8STOKEN